# Generated by Django 5.2 on 2025-09-17 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subject',
        ),
    ]
